### Numpy
* Numerical Python or numeric python
* Numpy is a programming language that deals with multi-dimensional arrays and matrices
* Numpy sypports a large number of mathematical operations

#### Why Use Numpy
* Numpy is memory efficiency,meaning it can handle the vast amount of data more accesible than any other library
* Especially for matrix multiplication and reshaping
* on top of that ,Numpy is fast.In fact,TensionFlow and Scikit

#### How To Install numpy
* Numpy is installed by defualt in anaconda

#### Arrays in Numpy

In [2]:
import numpy as np

In [6]:
print(np.__version__)

1.19.2


In [10]:
np.array([2,4,6,8])
print(np.array([2,4,6,8]))

[2 4 6 8]


In [15]:
data=np.array([[1,2,3,4],[5,6,7,8]])
print(data)

[[1 2 3 4]
 [5 6 7 8]]


In [18]:
# Mathematical Operations
a1=np.array([3,5,7,9])
a2=np.array([2,4,6,8])
print(a1+a2)
print(a1-a2)
print(a1*a2)
print(a1/a2)
print(a1**a2)
print(a1//a2)

[ 5  9 13 17]
[1 1 1 1]
[ 6 20 42 72]
[1.5        1.25       1.16666667 1.125     ]
[       9      625   117649 43046721]
[1 1 1 1]


In [19]:
#Shape of Array
data=np.array([[1,2,3,4],[5,6,7,8]])
print(np.shape(data))
print(data.dtype)

(2, 4)
int32


In [22]:
data1=np.array([[1.0,2.0,3.0,4.0],[5.0,6.0,7.0,8.0]])
print(np.shape(data1))
print(data1.dtype)

(2, 4)
float64


In [23]:
data1=np.array([[1.0,2.0,3.0,4.0],[5.0,6.0,7.0,8.0,1.02]])     #creates error
print(np.shape(data1))
print(data1.dtype)

(2,)
object


<ipython-input-23-2bf5e12a10cb>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  data1=np.array([[1.0,2.0,3.0,4.0],[5.0,6.0,7.0,8.0,1.02]])


In [25]:
#numpy zeros and ones
#numpy zeros
np.zeros((3,2),dtype=float)

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [26]:
np.zeros((3,2),dtype=str)

array([['', ''],
       ['', ''],
       ['', '']], dtype='<U1')

In [27]:
#numpy ones
np.ones((3,2),dtype=float)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [33]:
np.ones((3,2),dtype=str)

array([['1', '1'],
       ['1', '1'],
       ['1', '1']], dtype='<U1')

In [31]:
#numpy reshape
data=np.array([[1,2,3,4],[5,6,7,8]])
print(data)
data.reshape((4,2))

[[1 2 3 4]
 [5 6 7 8]]


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [32]:
#numpy flatten-returns all rows as a single row
data=np.array([[1,2,3,4],[5,6,7,8]])
data.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [36]:
#numpt hstack(data appended horizantally)
a1=np.array([3,5,7,9])
a2=np.array([2,4,6,8])
print(a1)
print(a2)
print(np.hstack((a1,a2)))
print(np.hstack((a1)))

[3 5 7 9]
[2 4 6 8]
[3 5 7 9 2 4 6 8]
[3 5 7 9]


In [38]:
a1=np.array([3,5,7,9])
a2=np.array([2,4,6,8])
print(a1)
print(a2)
print(np.vstack((a1)))

[3 5 7 9]
[2 4 6 8]
[[3]
 [5]
 [7]
 [9]]


In [40]:
#to calculate mean
data=np.array([[1,2,3,4],[5,6,7,8]])
print(data)
data.mean()

[[1 2 3 4]
 [5 6 7 8]]


4.5

In [47]:
#to calculate standard deviation,median,mod
data=np.array([[1,2,3,4],[5,6,7,8]])
print(data)
print(data.std())
print(np.median(data))
print(np.mod(2,3))

[[1 2 3 4]
 [5 6 7 8]]
2.29128784747792
4.5
2


In [57]:
#generate random numbers
d=np.random.randint(1,50,(3,3))
print(d)

[[34 44 24]
 [ 1 13  3]
 [17 44 38]]


In [58]:
#syntax---->np.random.normal(Loc(mean),scale(std),size(no.of elements))
np.random.normal(5,4,10)

array([ 3.5066921 ,  6.2392453 ,  2.23419276,  5.33421208,  8.85157403,
       11.3014546 ,  7.74251747,  0.2900681 ,  7.3988605 ,  6.47912529])

In [62]:
#numpy  statistical functions(min,max,mean,std,median)

In [59]:
d

array([[34, 44, 24],
       [ 1, 13,  3],
       [17, 44, 38]])

In [60]:
d.min()

1

In [61]:
d.max()

44

In [63]:
d.std()

15.760553979108572

In [67]:
#Transpose
print(d)
print(d.T)
print(d.transpose())

[[34 44 24]
 [ 1 13  3]
 [17 44 38]]
[[34  1 17]
 [44 13 44]
 [24  3 38]]
[[34  1 17]
 [44 13 44]
 [24  3 38]]


In [71]:
print(np.eye(3))
print(np.eye(3,dtype=int))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [72]:
print(a1)
print(a2)
a1.dot(a2)

[3 5 7 9]
[2 4 6 8]


140

In [73]:
d1=np.array([1,2,3,4])
print(np.array([d1,pow(d1,3)]))

[[ 1  2  3  4]
 [ 1  8 27 64]]


In [75]:
#repeat method
a=np.repeat([1,2,3,4],3)
print(a)

[1 1 1 2 2 2 3 3 3 4 4 4]


In [76]:
a=np.array([1,2,3,4]*3)
print(a)

[1 2 3 4 1 2 3 4 1 2 3 4]


In [79]:
#Arrange function
#Syntax--->arrange(Start,Stop,Step)
print(np.arange(1,11))

[ 1  2  3  4  5  6  7  8  9 10]


In [81]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [82]:
#numpy linspace
#syntax---->linspace(start,stop,endpoint)
np.linspace(1,5,num=10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [ ]:
#indexing slicing
